declare @a nvarchar(2000)
set @a='70e6fccb13b54a499763a8770114cdbc,b4f4aa05bc18439aa49aa877011433e0,da7376a65dd4437b8ccaa87701142b97,2568bbd54de14ff7a877a8770113944f,0315114f08a247d5bb92a877011393d9,beff25f10530483083e6a8770112f7c8,c4063d1491f34b848b3aa8770112dfbd,65738adbf02c40529cb1a87701123c6e,0636093792df48788862a8770111cb36,fa77b0e3e94145e0bc6da8770111894c,6e5bcd872cbd41509d1ca8770110df78,04940f8dfd214345a7eda8770110d5e3,02e6aee3467f419288dba877010f90cd,e9bd78b51c8f4713b269a877010f695a'

IF EXISTS(SELECT 1 FROM master.dbo.sysservers WHERE srvname='cloudSvr')   
begin   
	EXEC sp_droplinkedsrvlogin 'cloudSvr',NULL  
	EXEC sp_dropserver 'cloudSvr'   
end  

DECLARE @provider VARCHAR(50),@datasrc VARCHAR(50),@sa VARCHAR(50),@pwd VARCHAR(50)
SELECT @provider='SQLOLEDB',@datasrc='114.55.9.79',@sa='sa',@pwd='Ydl(,sql,)150925'

EXEC sp_addlinkedserver
@server='cloudSvr',--被访问的服务器别名（习惯上直接使用目标服务器IP，或取个别名如：JOY）
@srvproduct='',
@provider=@provider,
@datasrc=@datasrc --要访问的服务器

--使用sp_addlinkedsrvlogin 来增加用户登录链接

EXEC sp_addlinkedsrvlogin
'cloudSvr', --被访问的服务器别名（如果上面sp_addlinkedserver中使用别名JOY，则这里也是JOY）
'false',
NULL,
@sa, --帐号
@pwd --密码


DELETE from cloudSvr.YDL.dbo.Game WHERE Id IN(SELECT Id from [dbo].[fn_Split](@a))
DELETE from cloudSvr.YDL.dbo.Gamegroup WHERE GameId IN(select Id from [dbo].[fn_Split](@a))
DELETE from cloudSvr.YDL.dbo.GameGroupMember WHERE GameId IN(select Id from [dbo].[fn_Split](@a))
DELETE from cloudSvr.YDL.dbo.GameJudge WHERE GameId IN(select Id from [dbo].[fn_Split](@a))
DELETE from cloudSvr.YDL.dbo.GameLoopDetail WHERE LoopId IN(SELECT Id FROM GameLoop WHERE GameId IN (select Id from [dbo].[fn_Split](@a)))
DELETE from cloudSvr.YDL.dbo.GameLoopMap WHERE LoopId IN(SELECT Id FROM GameLoop WHERE GameId IN (select Id from [dbo].[fn_Split](@a)))
DELETE from cloudSvr.YDL.dbo.GameLoop WHERE GameId IN(select Id from [dbo].[fn_Split](@a))
DELETE from cloudSvr.YDL.dbo.GameOrder WHERE GameId IN(select Id from [dbo].[fn_Split](@a))
DELETE from cloudSvr.YDL.dbo.GameTeam WHERE GameId IN(select Id from [dbo].[fn_Split](@a))


INSERT INTO cloudSvr.YDL.dbo.Game([Id]
           ,[IsTop]
           ,[HeadUrl]
           ,[SportId]
           ,[ActivityId]
           ,[Name]
           ,[NameOption]
           ,[Introduce]
           ,[Prize]
           ,[GameRule]
           ,[ClubId]
           ,[KnockoutOption]
           ,[IsKnockOutAB]
           ,[BattleStyle]
           ,[BattleStyleCount]
           ,[TeamMode]
           ,[IsTeam]
           ,[IsLevelGame]
           ,[LevelValue]
           ,[CityId]
           ,[VenueId]
           ,[Cost]
           ,[Organizer]
           ,[SecondOrganizer]
           ,[RegBeginTime]
           ,[RegEndTime]
           ,[PlayBeginTime]
           ,[PlayEndTime]
           ,[IsScoreGame]
           ,[BeginScore]
           ,[EndScore]
           ,[State]
           ,[CreatorId]
           ,[CreateDate]
           ,[IsEnableTV]) SELECT [Id]
           ,[IsTop]
           ,[HeadUrl]
           ,[SportId]
           ,[ActivityId]
           ,[Name]
           ,[NameOption]
           ,[Introduce]
           ,[Prize]
           ,[GameRule]
           ,[ClubId]
           ,[KnockoutOption]
           ,[IsKnockOutAB]
           ,[BattleStyle]
           ,[BattleStyleCount]
           ,[TeamMode]
           ,[IsTeam]
           ,[IsLevelGame]
           ,[LevelValue]
           ,[CityId]
           ,[VenueId]
           ,[Cost]
           ,[Organizer]
           ,[SecondOrganizer]
           ,[RegBeginTime]
           ,[RegEndTime]
           ,[PlayBeginTime]
           ,[PlayEndTime]
           ,[IsScoreGame]
           ,[BeginScore]
           ,[EndScore]
           ,[State]
           ,[CreatorId]
           ,[CreateDate]
           ,[IsEnableTV] FROM dbo.Game WHERE Id IN(select Id from [dbo].[fn_Split](@a))
INSERT INTO cloudSvr.YDL.dbo.Gamegroup([Id]
      ,[GameId]
      ,[OrderId]
      ,[IsTeam]
      ,[OrderNo]
      ,[Name]
      ,[LeaderId]
      ,[TableNo]
      ,[CreateDate]) SELECT [Id]
      ,[GameId]
      ,[OrderId]
      ,[IsTeam]
      ,[OrderNo]
      ,[Name]
      ,[LeaderId]
      ,[TableNo]
      ,[CreateDate] FROM Gamegroup WHERE GameId IN(select Id from [dbo].[fn_Split](@a))
INSERT INTO cloudSvr.YDL.dbo.GameGroupMember([Id]
      ,[GameId]
      ,[GroupId]
      ,[OrderNo]
      ,[TeamId]
      ,[IsTeam]
      ,[GroupScore]
      ,[Rate]
      ,[RateRemark]
      ,[Rank]
      ,[Remark]
      ,[CreateDate]) SELECT [Id]
      ,[GameId]
      ,[GroupId]
      ,[OrderNo]
      ,[TeamId]
      ,[IsTeam]
      ,[GroupScore]
      ,[Rate]
      ,[RateRemark]
      ,[Rank]
      ,[Remark]
      ,[CreateDate] FROM GameGroupMember WHERE GameId IN(select Id from [dbo].[fn_Split](@a))
INSERT INTO cloudSvr.YDL.dbo.GameJudge([Id]
      ,[GameId]
      ,[UserId]
      ,[CreateDate]) SELECT [Id]
      ,[GameId]
      ,[UserId]
      ,[CreateDate] FROM GameJudge WHERE GameId IN(select Id from [dbo].[fn_Split](@a))
INSERT INTO cloudSvr.YDL.dbo.GameLoop([Id]
      ,[GameId]
      ,[GroupId]
      ,[OrderId]
      ,[OrderNo]
      ,[LoopOrderNo]
      ,[BeginRank]
      ,[EndRank]
      ,[IsExtra]
      ,[ExtraOrder]
      ,[ExtraWinOrder]
      ,[ExtraFailOrder]
      ,[Team1Id]
      ,[Team2Id]
      ,[TableNo]
      ,[BeginTime]
      ,[StartTime]
      ,[EndTime]
      ,[MasterJudgeId]
      ,[JudgeId]
      ,[IsTeam]
      ,[Score1]
      ,[Score2]
      ,[Team1]
      ,[Team2]
      ,[Game1]
      ,[Game2]
      ,[Fen1]
      ,[Fen2]
      ,[State]
      ,[CreateDate]
      ,[IsBye]
      ,[WaiverOption]
      ,[WinSign]
      ,[JudgeSign]
      ,[IsKnock]
      ,[KnockLoopId]
      ,[Remark]) SELECT [Id]
      ,[GameId]
      ,[GroupId]
      ,[OrderId]
      ,[OrderNo]
      ,[LoopOrderNo]
      ,[BeginRank]
      ,[EndRank]
      ,[IsExtra]
      ,[ExtraOrder]
      ,[ExtraWinOrder]
      ,[ExtraFailOrder]
      ,[Team1Id]
      ,[Team2Id]
      ,[TableNo]
      ,[BeginTime]
      ,[StartTime]
      ,[EndTime]
      ,[MasterJudgeId]
      ,[JudgeId]
      ,[IsTeam]
      ,[Score1]
      ,[Score2]
      ,[Team1]
      ,[Team2]
      ,[Game1]
      ,[Game2]
      ,[Fen1]
      ,[Fen2]
      ,[State]
      ,[CreateDate]
      ,[IsBye]
      ,[WaiverOption]
      ,[WinSign]
      ,[JudgeSign]
      ,[IsKnock]
      ,[KnockLoopId]
      ,[Remark] FROM GameLoop WHERE GameId IN(select Id from [dbo].[fn_Split](@a))
INSERT INTO cloudSvr.YDL.dbo.GameLoopDetail([Id]
      ,[LoopId]
      ,[MapId]
      ,[IsTeam]
      ,[Team1Id]
      ,[User1Id]
      ,[Team2Id]
      ,[User2Id]
      ,[OrderNo]
      ,[Fen1]
      ,[Fen2]
      ,[CreateDate]) SELECT [Id]
      ,[LoopId]
      ,[MapId]
      ,[IsTeam]
      ,[Team1Id]
      ,[User1Id]
      ,[Team2Id]
      ,[User2Id]
      ,[OrderNo]
      ,[Fen1]
      ,[Fen2]
      ,[CreateDate] FROM GameLoopDetail WHERE LoopId IN(SELECT Id FROM GameLoop WHERE GameId IN (select Id from [dbo].[fn_Split](@a)))
INSERT INTO cloudSvr.YDL.dbo.GameLoopMap([Id]
      ,[LoopId]
      ,[OrderNo]
      ,[IsTeam]
      ,[Team1Id]
      ,[User1Id]
      ,[User1Name]
      ,[Team2Id]
      ,[User2Id]
      ,[User2Name]
      ,[Game1]
      ,[Game2]
      ,[Fen1]
      ,[Fen2]
      ,[WaiverOption]
      ,[WinGame]
      ,[WinSign]
      ,[JudgeSign]
      ,[CreateDate]) SELECT [Id]
      ,[LoopId]
      ,[OrderNo]
      ,[IsTeam]
      ,[Team1Id]
      ,[User1Id]
      ,[User1Name]
      ,[Team2Id]
      ,[User2Id]
      ,[User2Name]
      ,[Game1]
      ,[Game2]
      ,[Fen1]
      ,[Fen2]
      ,[WaiverOption]
      ,[WinGame]
      ,[WinSign]
      ,[JudgeSign]
      ,[CreateDate] FROM GameLoopMap WHERE LoopId IN(SELECT Id FROM GameLoop WHERE GameId IN (select Id from [dbo].[fn_Split](@a)))

INSERT INTO cloudSvr.YDL.dbo.GameOrder([Id]
      ,[GameId]
      ,[PreOrderId]
      ,[NextOrderId]
      ,[NextOrderBId]
      ,[OrderNo]
      ,[Name]
      ,[IsTeam]
      ,[TeamScoreMode]
      ,[KnockoutOption]
      ,[KnockoutCount]
      ,[KnockoutTotal]
      ,[BeginRank]
      ,[EndRank]
      ,[GroupCount]
      ,[CreateDate]
      ,[State]
      ,[IsExtra]
      ,[WinTeam]
      ,[WinGame]
      ,[KnockOutAB]) SELECT [Id]
      ,[GameId]
      ,[PreOrderId]
      ,[NextOrderId]
      ,[NextOrderBId]
      ,[OrderNo]
      ,[Name]
      ,[IsTeam]
      ,[TeamScoreMode]
      ,[KnockoutOption]
      ,[KnockoutCount]
      ,[KnockoutTotal]
      ,[BeginRank]
      ,[EndRank]
      ,[GroupCount]
      ,[CreateDate]
      ,[State]
      ,[IsExtra]
      ,[WinTeam]
      ,[WinGame]
      ,[KnockOutAB] FROM GameOrder WHERE GameId IN(select Id from [dbo].[fn_Split](@a))
INSERT INTO cloudSvr.YDL.dbo.GameTeam([Id]
      ,[HeadUrl]
      ,[GameId]
      ,[IsTeam]
      ,[TeamName]
      ,[TeamUserId]
      ,[TeamUserName]
      ,[Cost]
      ,[IsPayCost]
      ,[Remark]
      ,[State]
      ,[AuditorId]
      ,[AuditRemark]
      ,[AuditDate]
      ,[IsSeed]
      ,[SeedNo]
      ,[MobilePhone]
      ,[IsJoined]
      ,[CompanyId]
      ,[CorpTeamId]
      ,[CorpTeamName]
      ,[CreatorId]
      ,[CreateDate]
      ,[NationalId]) SELECT [Id]
      ,[HeadUrl]
      ,[GameId]
      ,[IsTeam]
      ,[TeamName]
      ,[TeamUserId]
      ,[TeamUserName]
      ,[Cost]
      ,[IsPayCost]
      ,[Remark]
      ,[State]
      ,[AuditorId]
      ,[AuditRemark]
      ,[AuditDate]
      ,[IsSeed]
      ,[SeedNo]
      ,[MobilePhone]
      ,[IsJoined]
      ,[CompanyId]
      ,[CorpTeamId]
      ,[CorpTeamName]
      ,[CreatorId]
      ,[CreateDate]
      ,[NationalId] FROM GameTeam WHERE GameId IN(select Id from [dbo].[fn_Split](@a))

